language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

script:
  - cd react-cicd
  - yarn test
  - yarn run build
  - yarn run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
    branch: master