language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

script:
  - cd react-cicd
  - yarn test
  - yarn run build
  
after_success:
  - git config --global user.name "akhila2019"
  - git config --global user.email "akhila@esquareit.com"
  - git remote rm origin
  - git remote add origin https://akhila2019:${GH_TOKEN}@https://github.com/akhila2019/react-cicd.git
  - npm run deploy
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
    branch: master